language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Cache 활성화
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

install: gradle wrapper --gradle-version 5.6.4

# clean 후 Build (Build시 자동으로 test 수행)
script:
  - "./gradlew clean build"